### ISSUE TITLE
Old Auth0 Lib

### ISSUE THREAD

**Issue by stevezau** [auth0-samples/auth0-ios-swift-sample#51]
Hi,

I was testing this sample for SSO from mobile to web. Didn't work due to an old auth0 lib not using safari view controller. I must of installed the pod ages ago as i had an old version.. 

We may want to update the lib version

https://github.com/auth0-samples/auth0-ios-swift-sample/blob/master/05-Authorization/Podfile#L6

**Comment by stevezau** [comment]
@cocojoe should the podfile's be fixed? The 03-Sessions use case does not even work.I get a seg fault.

**Comment by cocojoe** [comment]
@stevezau to clarify, you are running the sample as is, they only difference is you update the pod to the latest version, can you just paste in the contents of your `Podfile.lock`.
We should probably update the Pods yes. However, let's deal with the seg fault first.

What version of Xcode? What are the reproducible steps I can take to recreate this.

Thanks

**Comment by stevezau** [comment]
Hi @cocojoe,

I upgraded to the latest auth0 pod and restarted, 03 seems to work now.

I also deployed 08 to my ios iphone x. When running the app, it opens the home page, when clicking login it crashes. As it's running on iphone i'm not sure how to get crash report? Obviously it won't work via simulator as no touch id?

**Comment by cocojoe** [comment]
Let me check 08 and report back.

**Comment by cocojoe** [comment]
@stevezau in general it's important that anyone who submits an issue provides the details asked for so we can try and replicate your issue or resolve any environment issues.

I tried sample `08` on my iPhone X using Xcode 10.0.

- `pod --version` 1.5.3

```
// Podfile.lock
PODS:
  - Auth0 (1.13.0):
    - SimpleKeychain
  - SimpleKeychain (0.8.1)
```

If you are debugging (just hitting run) from Xcode 10 to your iPhone X either via cable or wireless deployment, Xcode will still show the logs so any crash information should be displayed.
Also in the simulator does allow Face ID / Touch ID support, it's not as fluid as the real thing. However, it does work. Have a look in the simulator menu.

<img width="264" alt="screenshot 2018-10-24 at 14 51 07" src="https://user-images.githubusercontent.com/928115/47435480-9cc7a600-d79c-11e8-97c0-f03e81044fd1.png">

**Xcode Debug Information**
<img width="1396" alt="screenshot 2018-10-24 at 14 50 01" src="https://user-images.githubusercontent.com/928115/47435342-507c6600-d79c-11e8-89d5-2e6c9ed92317.png">

**Crash**

So it never showed up for me on first run, it looks like there is a policy flag that now has to be set once you access biometrics. I'll look into this and update on my findings.

**Comment by cocojoe** [comment]
The following flag [NSFaceIDUsageDescription](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW75) needs to be added to `Info.plist`.

Will add this test and then update the sample.

**Comment by stevezau** [comment]
Hi @cocojoe, thanks. I'm in no way an iOS developer so was a little tricky for me to work out what was going on.

Setting NSFaceIDUsageDescription fixed it for me. It no longer crashes. FaceID Auth works also.

So i guess two things are required
1. Update pod to use latest version of auth0 lib
2. Add  NSFaceIDUsageDescription to Info.plist or instructions in the readme.

**Comment by cocojoe** [comment]
@stevezau I've updated all the samples to latest pods and added/tested the NSFaceIDUsageDescription in the Touch ID/Face ID sample chapter.

Thanks for reporting 👍 
I've asked Docs & Quickstarts to add the usage of `NSFaceIDUsageDescription`

**Comment by jimmyjames** [comment]
Hi @stevezau as the samples have been updated and I see the docs were updated with info about `NSFaceIDUsageDescription`, I'm going to close this issue. If you continue to have trouble with this topic, don't hesitate to reopen this issue or create a new one (just be sure to include any updated information so we can assist). Thanks! 👍
